#define SERVER_PORT 8080
#define SERVER_IP "127.0.0.1"

#define MAX_PORT 65535
#define MIN_PORT 1024

#define MAX_WORKERS 100
#define MIN_WORKERS 1

#define USR_ALREADY_TAKEN -50
#define MAIL_ALREADY_TAKEN -51
#define USR_NOT_FOUND -52
#define WRONG_PASSWORD -53
#define GENERIC_ERROR_ON_LOGIN -54
#define GENERIC_ERROR_ON_REGISTER -55

#define BASE_CODE 20
#define EXIT_CODE 20
#define LOGIN_CODE 21
#define REGISTER_CODE 22

#define LOGIN_SUCCESS 30
#define REGISTER_SUCCESS 31

#define LIST_REQUEST 40
#define GET_REQUEST 41
#define ADD_REQUEST 42

#define USER_MAX_SIZE 16
#define MAIL_MAX_SIZE 32
#define PASSWORD_MAX_SIZE 8

#define EPH_KEY_SIZE 1024
#define RSA_KEY_SIZE 2048
#define AES_BLOCK_SIZE 16
#define ENCRYPTED_SIGNATURE_SIZE 272
#define HMAC_DIGEST_SIZE 32
