#define SERVER_PORT 8080
#define SERVER_IP "127.0.0.1"

#define MAX_PORT 65535
#define MIN_PORT 1024

#define MAX_WORKERS 100
#define MIN_WORKERS 1

#define USR_ALREADY_TAKEN -50
#define MAIL_ALREADY_TAKEN -51
#define USR_NOT_FOUND -52
#define WRONG_PASSWORD -53
#define GENERIC_ERROR_ON_LOGIN -54
#define GENERIC_ERROR_ON_REGISTER -55
#define OTP_MISMATCH -56
#define ACK 1

#define BASE_CODE 20
#define EXIT_CODE 20
#define LOGIN_CODE 21
#define REGISTER_CODE 22
#define LIST_CODE 21
#define GET_CODE 22
#define ADD_CODE 23

#define LOGIN_SUCCESS 30
#define REGISTER_SUCCESS 31

#define USER_MAX_SIZE 16
#define MAIL_MAX_SIZE 32
#define PASSWORD_MAX_SIZE 8
#define OTP_SIZE 6

#define EPH_KEY_SIZE 1024
#define RSA_KEY_SIZE 2048
#define AES_BLOCK_SIZE 16
#define ENCRYPTED_SIGNATURE_SIZE 272
#define HMAC_DIGEST_SIZE 32
#define HASHED_PASSWORD_SIZE 64
#define PASSWORD_SIZE 32
#define SESSION_KEY_LENGTH 256
#define DECRYPTED_SIGNATURE_SIZE 256

#define PWD_MESSAGE1_SIZE       HASHED_PASSWORD_SIZE*sizeof(uint8_t) + sizeof(uint32_t)

#define ID_SIZE sizeof(uint32_t)
#define NAME_SIZE USER_MAX_SIZE*sizeof(uint8_t)
#define MAX_TITLE_SIZE 64
#define MAX_BODY_SIZE 256

#define MAX_MESSAGE_SIZE ID_SIZE + NAME_SIZE + MAX_TITLE_SIZE + MAX_BODY_SIZE